name: Pruebita

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run:
          sudo apt-get update

          if ! command -v docker-compose &> /dev/null; then
            echo "Docker no encontrado. Instalando..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose ya esta instalado"
          fi

          docker --version
          docker-compose --version

      
      - name: Log in to DockerHub
        uses: docker/login-action@v2      
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    
      - name: Build and push Docker images with Docker Compose
        run: │
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push



          
