name: Pruebita

on:
  push:
    branches:
      - main  # Cambia según sea necesario

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Build manual (mejor que usar docker-compose para subir)
      - name: Build Docker image
        run: |
          docker build -t melany555/pruebita1:latest .

      # Paso 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push melany555/pruebita1:latest

      # Paso 5: Verificar imágenes locales (debug)
      - name: List Docker images
        run: docker images



          
